name: Build and deploy Node.js project to Azure Function App - story-vault-api-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./dist"
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Copy host.json to dist
        run: |
          Copy-Item -Path "host.json" -Destination "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/host.json" -Force
        shell: pwsh

      - name: List dist contents
        run: Get-ChildItem -Recurse -Path "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_45E312CE8F3544688F004C622E562FFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4ABF6F2431F44A8FA4BC9BC2306FFB13 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A8695FFFA51423EB40445BE5893E3A2 }}

      - name: Copy host.json to output
        run: Copy-Item -Path "${{ github.workspace }}/host.json" -Destination "./output/host.json" -Force
        shell: pwsh

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: "story-vault-api-dev"
          slot-name: "Production"
          package: "./output"
