# Docs: https://github.com/Azure/functions-action

name: Build and deploy Node.js project to Azure Function App - story-vault-api-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./dist"
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Build, and Test
        shell: pwsh
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          Copy-Item -Path "host.json" -Destination "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/host.json"

      - name: Debug Output Structure
        run: dir ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} /s
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./output

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_45E312CE8F3544688F004C622E562FFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4ABF6F2431F44A8FA4BC9BC2306FFB13 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A8695FFFA51423EB40445BE5893E3A2 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "story-vault-api-dev"
          slot-name: "Production"
          package: "./output"
